#!/bin/bash

# Check if it is running and get PID
pgrep rtl_433

/usr/bin/php -q REPLACELBPHTMLDIR/create_conf.php &

exitcode=$?
if [[ $exitcode != 0 ]]; 
then
	# Restart if not
	systemctl restart rtl_433-mqtt.service
	sleep 5
fi

exit 0
