#!/bin/bash

# Bashscript which is executed by bash when uninstalling the plugin
# Use with caution and remember, that all systems may be different!
#
# Exit code must be 0 if executed successfull. 
# Exit code 1 gives a warning but continues deinstallation.
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# Will be executed as user "root".
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
# You can use all vars from /etc/environment in this script.
#
# We add 5 additional arguments when executing this script:
# command <TEMPFOLDER> <NAME> <FOLDER> <VERSION> <BASEFOLDER>
#
# For logging, print to STDOUT. You can use the following tags for showing
# different colorized information during plugin installation:
#
# <OK> This was ok!"
# <INFO> This is just for your information."
# <WARNING> This is a warning!"
# <ERROR> This is an error!"
# <FAIL> This is a fail!"

# To use important variables from command line use the following code:
COMMAND=$0    # Zero argument is shell command
PTEMPDIR=$1   # First argument is temp folder during install
PSHNAME=$2    # Second argument is Plugin-Name for scipts etc.
PDIR=$3       # Third argument is Plugin installation folder
PVERSION=$4   # Forth argument is Plugin version
#LBHOMEDIR=$5 # Comes from /etc/environment now. Fifth argument is
              # Base folder of LoxBerry

# Combine them with /etc/environment
PCGI=$LBPCGI/$PDIR
PHTML=$LBPHTML/$PDIR
PTEMPL=$LBPTEMPL/$PDIR
PDATA=$LBPDATA/$PDIR
PLOG=$LBPLOG/$PDIR # Note! This is stored on a Ramdisk now!
PCONFIG=$LBPCONFIG/$PDIR
PSBIN=$LBPSBIN/$PDIR
PBIN=$LBPBIN/$PDIR

sudo systemctl stop rtl_433-mqtt.service
sudo systemctl disable rtl_433-mqtt.service
sudo apt-get purge --auto-remove rtl-sdr 
sudo apt-get purge --auto-remove rtl_433
rm -r /usr/local/rtl/rtl-sdr
rm -r /usr/local/rtl/rtl_433
rm /usr/local/rtl/*
rm -r /usr/local/rtl
rm /etc/modprobe.d/no-rtl.conf
rm /etc/systemd/system/rtl_433-mqtt.service
rm /etc/udev/rules.d/rtl-sdr.rules

# Exit with Status 0
exit 0
